// Regenerates src/themes/index.ts from the files in src/themes/.
//
//   node scripts/build-themes.mjs
//
// The barrel is generated rather than hand-edited for one reason: a workshop can add a
// hundred theme files in an afternoon, and a hand-edited barrel would make every one of
// those pull requests conflict with every other. Contributors add a file and nothing else.
import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, "..", "src", "themes");

const skip = new Set(["index.ts", "types.ts"]);
const files = readdirSync(dir)
  .filter((f) => f.endsWith(".ts") && !f.startsWith("_") && !skip.has(f))
  .sort();

const names = files.map((f) => f.replace(/\.ts$/, ""));
// `theme_<handle>`: handles contain hyphens, which are not legal in an identifier.
const ident = (name) => `theme_${name.replace(/[^A-Za-z0-9]/g, "_")}`;

const body = `// Generated by scripts/build-themes.mjs. Do not edit by hand.
// Add a theme by adding a file to this folder, then re-run the script.
import type { Theme } from "./types";
${names.map((n) => `import ${ident(n)} from "./${n}";`).join("\n")}

export type { Theme } from "./types";

/** Every community theme, by the file name it was contributed as. */
export const themes: Record<string, Theme> = {
${names.map((n) => `  "${n}": ${ident(n)},`).join("\n")}
};

export const themeList: Theme[] = Object.values(themes);
`;

writeFileSync(join(dir, "index.ts"), body);
console.log(`wrote ${names.length} theme(s) to src/themes/index.ts`);
