// Generated by scripts/build-themes.mjs. Do not edit by hand.
// Add a theme by adding a file to this folder, then re-run the script.
import type { Theme } from "./types";
import theme_vineethpawar from "./vineethpawar";

export type { Theme } from "./types";

/** Every community theme, by the file name it was contributed as. */
export const themes: Record<string, Theme> = {
  "vineethpawar": theme_vineethpawar,
};

export const themeList: Theme[] = Object.values(themes);
