/**
 * GENERATED by scripts/gen-lucide-pack.mjs — do not edit by hand.
 *
 * Geometry from lucide (https://lucide.dev, ISC license), parsed into
 * IconDef elements so web and native render identically through the
 * registry. Brand icons (github, linkedin) carry the classic
 * feather-lineage paths, which lucide has since removed upstream.
 * Regenerate: cd packages/icons && node scripts/gen-lucide-pack.mjs
 */
import type { IconDef } from "../registry";

export const lucidePack = {
  "arrow-down": {"elements":[{"kind":"path","d":"M12 5v14"},{"kind":"path","d":"m19 12-7 7-7-7"}]},
  "arrow-left": {"elements":[{"kind":"path","d":"m12 19-7-7 7-7"},{"kind":"path","d":"M19 12H5"}]},
  "arrow-right": {"elements":[{"kind":"path","d":"M5 12h14"},{"kind":"path","d":"m12 5 7 7-7 7"}]},
  "arrow-up": {"elements":[{"kind":"path","d":"m5 12 7-7 7 7"},{"kind":"path","d":"M12 19V5"}]},
  "backspace": {"elements":[{"kind":"path","d":"M10 5a2 2 0 0 0-1.344.519l-6.328 5.74a1 1 0 0 0 0 1.481l6.328 5.741A2 2 0 0 0 10 19h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2z"},{"kind":"path","d":"m12 9 6 6"},{"kind":"path","d":"m18 9-6 6"}]},
  "briefcase": {"elements":[{"kind":"path","d":"M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"},{"kind":"rect","x":2,"y":6,"width":20,"height":14,"rx":2}]},
  "check": {"elements":[{"kind":"path","d":"M20 6 9 17l-5-5"}]},
  "chevron-down": {"elements":[{"kind":"path","d":"m6 9 6 6 6-6"}]},
  "chevron-left": {"elements":[{"kind":"path","d":"m15 18-6-6 6-6"}]},
  "chevron-right": {"elements":[{"kind":"path","d":"m9 18 6-6-6-6"}]},
  "chevron-up": {"elements":[{"kind":"path","d":"m18 15-6-6-6 6"}]},
  "copy": {"elements":[{"kind":"rect","x":8,"y":8,"width":14,"height":14,"rx":2},{"kind":"path","d":"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"}]},
  "download": {"elements":[{"kind":"path","d":"M12 15V3"},{"kind":"path","d":"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"},{"kind":"path","d":"m7 10 5 5 5-5"}]},
  "enter": {"elements":[{"kind":"path","d":"M20 4v7a4 4 0 0 1-4 4H4"},{"kind":"path","d":"m9 10-5 5 5 5"}]},
  "external-link": {"elements":[{"kind":"path","d":"M15 3h6v6"},{"kind":"path","d":"M10 14 21 3"},{"kind":"path","d":"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"}]},
  "eye": {"elements":[{"kind":"path","d":"M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"},{"kind":"circle","cx":12,"cy":12,"r":3}]},
  "file-down": {"elements":[{"kind":"path","d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"},{"kind":"path","d":"M14 2v5a1 1 0 0 0 1 1h5"},{"kind":"path","d":"M12 18v-6"},{"kind":"path","d":"m9 15 3 3 3-3"}]},
  "file-text": {"elements":[{"kind":"path","d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"},{"kind":"path","d":"M14 2v5a1 1 0 0 0 1 1h5"},{"kind":"path","d":"M10 9H8"},{"kind":"path","d":"M16 13H8"},{"kind":"path","d":"M16 17H8"}]},
  "gem": {"elements":[{"kind":"path","d":"M10.5 3 8 9l4 13 4-13-2.5-6"},{"kind":"path","d":"M17 3a2 2 0 0 1 1.6.8l3 4a2 2 0 0 1 .013 2.382l-7.99 10.986a2 2 0 0 1-3.247 0l-7.99-10.986A2 2 0 0 1 2.4 7.8l2.998-3.997A2 2 0 0 1 7 3z"},{"kind":"path","d":"M2 9h20"}]},
  "git-branch": {"elements":[{"kind":"path","d":"M15 6a9 9 0 0 0-9 9V3"},{"kind":"circle","cx":18,"cy":6,"r":3},{"kind":"circle","cx":6,"cy":18,"r":3}]},
  "github": {"elements":[{"kind":"path","d":"M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65S8.93 17.38 9 18v4"},{"kind":"path","d":"M9 18c-4.51 2-5-2-7-2"}]},
  "grip": {"elements":[{"kind":"circle","cx":9,"cy":12,"r":1},{"kind":"circle","cx":9,"cy":5,"r":1},{"kind":"circle","cx":9,"cy":19,"r":1},{"kind":"circle","cx":15,"cy":12,"r":1},{"kind":"circle","cx":15,"cy":5,"r":1},{"kind":"circle","cx":15,"cy":19,"r":1}]},
  "heart": {"elements":[{"kind":"path","d":"M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"}]},
  "heart-filled": {"filled":true,"elements":[{"kind":"path","d":"M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"}]},
  "kebab": {"elements":[{"kind":"circle","cx":12,"cy":12,"r":1},{"kind":"circle","cx":19,"cy":12,"r":1},{"kind":"circle","cx":5,"cy":12,"r":1}]},
  "layout-template": {"elements":[{"kind":"rect","x":3,"y":3,"width":18,"height":7,"rx":1},{"kind":"rect","x":3,"y":14,"width":9,"height":7,"rx":1},{"kind":"rect","x":16,"y":14,"width":5,"height":7,"rx":1}]},
  "linkedin": {"elements":[{"kind":"path","d":"M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4V8h4v2a6 6 0 0 1 2-2z"},{"kind":"rect","x":2,"y":9,"width":4,"height":12},{"kind":"circle","cx":4,"cy":4,"r":2}]},
  "maximize": {"elements":[{"kind":"path","d":"M15 3h6v6"},{"kind":"path","d":"m21 3-7 7"},{"kind":"path","d":"m3 21 7-7"},{"kind":"path","d":"M9 21H3v-6"}]},
  "menu": {"elements":[{"kind":"path","d":"M4 5h16"},{"kind":"path","d":"M4 12h16"},{"kind":"path","d":"M4 19h16"}]},
  "minimize": {"elements":[{"kind":"path","d":"m14 10 7-7"},{"kind":"path","d":"M20 10h-6V4"},{"kind":"path","d":"m3 21 7-7"},{"kind":"path","d":"M4 14h6v6"}]},
  "minus": {"elements":[{"kind":"path","d":"M5 12h14"}]},
  "moon": {"elements":[{"kind":"path","d":"M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"}]},
  "palette": {"elements":[{"kind":"path","d":"M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z"},{"kind":"circle","cx":13.5,"cy":6.5,"r":0.5},{"kind":"circle","cx":17.5,"cy":10.5,"r":0.5},{"kind":"circle","cx":6.5,"cy":12.5,"r":0.5},{"kind":"circle","cx":8.5,"cy":7.5,"r":0.5}]},
  "pencil": {"elements":[{"kind":"path","d":"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"},{"kind":"path","d":"m15 5 4 4"}]},
  "plus": {"elements":[{"kind":"path","d":"M5 12h14"},{"kind":"path","d":"M12 5v14"}]},
  "redo": {"elements":[{"kind":"path","d":"m15 14 5-5-5-5"},{"kind":"path","d":"M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13"}]},
  "search": {"elements":[{"kind":"path","d":"m21 21-4.34-4.34"},{"kind":"circle","cx":11,"cy":11,"r":8}]},
  "settings": {"elements":[{"kind":"path","d":"M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"},{"kind":"circle","cx":12,"cy":12,"r":3}]},
  "share": {"elements":[{"kind":"circle","cx":18,"cy":5,"r":3},{"kind":"circle","cx":6,"cy":12,"r":3},{"kind":"circle","cx":18,"cy":19,"r":3},{"kind":"line","x1":0,"y1":0,"x2":0,"y2":0},{"kind":"line","x1":0,"y1":0,"x2":0,"y2":0}]},
  "sparkles": {"elements":[{"kind":"path","d":"M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z"},{"kind":"path","d":"M20 2v4"},{"kind":"path","d":"M22 4h-4"},{"kind":"circle","cx":4,"cy":20,"r":2}]},
  "star": {"elements":[{"kind":"path","d":"M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"}]},
  "sun": {"elements":[{"kind":"circle","cx":12,"cy":12,"r":4},{"kind":"path","d":"M12 2v2"},{"kind":"path","d":"M12 20v2"},{"kind":"path","d":"m4.93 4.93 1.41 1.41"},{"kind":"path","d":"m17.66 17.66 1.41 1.41"},{"kind":"path","d":"M2 12h2"},{"kind":"path","d":"M20 12h2"},{"kind":"path","d":"m6.34 17.66-1.41 1.41"},{"kind":"path","d":"m19.07 4.93-1.41 1.41"}]},
  "trophy": {"elements":[{"kind":"path","d":"M10 14.66V17a1 1 0 0 1-1 1 2 2 0 0 0-2 2v2"},{"kind":"path","d":"M14 14.66V17a1 1 0 0 0 1 1 2 2 0 0 1 2 2v2"},{"kind":"path","d":"M17.916 10H19.5A2.5 2.5 0 0 0 22 7.5V5a1 1 0 0 0-1-1h-3"},{"kind":"path","d":"M4 22h16"},{"kind":"path","d":"M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1z"},{"kind":"path","d":"M6.084 10H4.5A2.5 2.5 0 0 1 2 7.5V5a1 1 0 0 1 1-1h3"}]},
  "undo": {"elements":[{"kind":"path","d":"M9 14 4 9l5-5"},{"kind":"path","d":"M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11"}]},
  "upload": {"elements":[{"kind":"path","d":"M12 3v12"},{"kind":"path","d":"m17 8-5-5-5 5"},{"kind":"path","d":"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"}]},
  "users": {"elements":[{"kind":"path","d":"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"},{"kind":"path","d":"M16 3.128a4 4 0 0 1 0 7.744"},{"kind":"path","d":"M22 21v-2a4 4 0 0 0-3-3.87"},{"kind":"circle","cx":9,"cy":7,"r":4}]},
  "warning": {"elements":[{"kind":"path","d":"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"},{"kind":"path","d":"M12 9v4"},{"kind":"path","d":"M12 17h.01"}]},
  "x": {"elements":[{"kind":"path","d":"M18 6 6 18"},{"kind":"path","d":"m6 6 12 12"}]},
  "zoom-in": {"elements":[{"kind":"circle","cx":11,"cy":11,"r":8},{"kind":"line","x1":0,"y1":0,"x2":0,"y2":0},{"kind":"line","x1":0,"y1":0,"x2":0,"y2":0},{"kind":"line","x1":0,"y1":0,"x2":0,"y2":0}]},
  "zoom-out": {"elements":[{"kind":"circle","cx":11,"cy":11,"r":8},{"kind":"line","x1":0,"y1":0,"x2":0,"y2":0},{"kind":"line","x1":0,"y1":0,"x2":0,"y2":0}]},
} as const satisfies Record<string, IconDef>;

export type LucidePackName = keyof typeof lucidePack;
